- name: SonarQube Scan
  shell: cmd
  env:
    SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
  run: |
    "C:\sonar-scanner\bin\sonar-scanner.bat" ^
      -Dsonar.projectKey=Projet-react ^
      -Dsonar.sources=. ^
      -Dsonar.host.url=%SONAR_HOST_URL% ^
      -Dsonar.token=%SONAR_TOKEN%
